---
- hosts: localhost
  gather_facts: no
#  vars_files:
#    - demo.yml
#    - globals.yml
  vars:
    input: &input
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
  tasks:
  - name: Get Ontapi version
    na_ontap_gather_facts:
      state: info
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      ontapi: 32
      validate_certs: false
  - import_role:
      name: schmots1.na_ontap_cluster_config
    vars: 
      <<: *input
  - import_role:
      name: schmots1.na_ontap_vserver_create
    vars:
      <<: *input
  - import_role:
      name: schmots1.na_ontap_nas_create
    vars: 
      <<: *input
